imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: "%cookie_name%"
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  'session.handler.native_file'
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  'UTF8'
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: 'memory' }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles:        [ 'AppBundle' ]

    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.js"
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css"
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css"
            filters: [ 'cssrewrite' ]

        bootstrap_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf"
            output: 'fonts/glyphicons-halflings-regular.ttf'
        bootstrap_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot"
            output: 'fonts/glyphicons-halflings-regular.eot'
        bootstrap_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg"
            output: 'fonts/glyphicons-halflings-regular.svg'
        bootstrap_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"
            output: 'fonts/glyphicons-halflings-regular.woff'

        jquery:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"

#FOS User Bundle
fos_user:
    db_driver: 'orm' # other valid values are 'mongodb' and 'couchdb'
    firewall_name: 'main'
    user_class: 'AppBundle\Entity\User'
    service:
        user_manager: 'OAuth2Framework\Component\Server\Model\UserAccount\UserAccountManagerInterface'
    from_email:
        address: 'test@foo.com'
        sender_name: 'test@foo.com'

jose:
    key_sets:
        signature:
            auto:
                storage_path: "%kernel.cache_dir%/signature.keyset"
                is_rotatable: true
                nb_keys: 2
                key_configuration:
                    kty: 'RSA'
                    size: 4096
                    alg: 'RS256'
                    use: 'sig'
        encryption:
            auto:
                storage_path: "%kernel.cache_dir%/encryption.keyset"
                is_rotatable: true
                nb_keys: 2
                key_configuration:
                    kty: 'RSA'
                    size: 4096
                    alg: 'RSA-OAEP-256'
                    use: 'enc'
        all_in_one:
            jwksets:
                id:
                    - 'jose.key_set.signature'
                    - 'jose.key_set.encryption'
        all_in_one_public:
            public_jwkset:
                id: 'jose.key_set.all_in_one'
                path: '/public.jwkset'

oauth2_server:
    server_uri: 'https://oauth2.test/'
    user_account:
        manager: 'OAuth2Framework\Component\Server\Model\UserAccount\UserAccountManagerInterface'
        repository: 'OAuth2Framework\Component\Server\Model\UserAccount\UserAccountRepositoryInterface'
#    resource_server:
#        enabled: false
#        repository: 'ResourceServerRepository::class'
#    scope:
#        enabled: true
#        available_scope: ['openid', 'email', 'profile', 'address', 'phone', 'offline_access']
#        policy:
#            default: 'none'
#            error:
#                enabled: true
#            default:
#                enabled: true
#                scope: ['openid']
#    access_token:
#        lifetime: 1800
#        jwt:
#            enabled: true
#            issuer: 'https://my.authorization.server/'
#            signature_algorithm: 'RS256'
#            signature_key_set: 'jose.key_set.signature'
#            key_encryption_algorithm: 'RSA-OAEP-256'
#            content_encryption_algorithm: 'A256CBC-HS512'
#            key_encryption_key_set: 'jose.key_set.encryption'
#        random_string:
#            enabled: true
#            min_length: 50
#            max_length: 100
    token_type:
        default: 'Bearer'
        bearer_token:
            enabled: true
            realm: 'My super service'
            authorization_header: true
            query_string: true
            request_body: true
        mac_token:
            enabled: true
            min_length: 50
            max_length: 100
            algorithm: 'hmac-sha-256'
            timestamp_lifetime: 10
    token_endpoint_auth_method:
        none:
            enabled: true
        client_secret_post:
            enabled: true
        client_secret_basic:
            enabled: true
            realm: 'My OAuth2 Server'
        client_assertion_jwt:
            enabled: true
            signature_algorithms: ['RS256', 'RS512', 'HS256', 'HS512', 'ES256', 'ES512']
            claim_checkers: ['exp', 'iat', 'nbf']
            header_checkers: ['crit']
            encryption:
                enabled: true
                required: false
                key_set: 'jose.key_set.encryption'
                key_encryption_algorithms: ['RSA-OAEP-256']
                content_encryption_algorithms: ['A128CBC-HS256']
    endpoint:
        client_registration:
            enabled: true
            path: '/client/management'
            initial_access_token:
                enabled: true
                required: false
                realm: 'Client Registration'
                class: 'AppBundle\Entity\InitialAccessToken'
            software_statement:
                enabled: true
                required: false
                key_set: 'jose.key_set.signature'
                allowed_signature_algorithms: ['RS256']
        client_configuration:
            enabled: true
            realm: 'Client Configuration'
            path: '/client/configure/{client_id}'
        token_revocation:
            enabled: true
            path: '/token/revocation'
            allow_callback: true
#        token_introspection:
#            enabled: true
#            path: '/token/introspection'
        token:
            enabled: true
            path: '/token/get'
        userinfo:
            enabled: true
            path: '/userinfo'
            signature:
                enabled: true
                signature_algorithms: ['RS256', 'RS512', 'HS256', 'HS512', 'ES256', 'ES512', 'none']
                key_set: 'jose.key_set.signature'
#            encryption:
#                enabled: true
#                key_set: 'jose.key_set.encryption'
#                key_encryption_algorithms: ['RSA-OAEP-256']
#                content_encryption_algorithms: ['A128CBC-HS256']
        jwks_uri:
            enabled: true
            route_name: 'jwkset_all_in_one_public_json'
#        metadata:
#            enabled: true
#            path: '/.well-known/openid-configuration'
        session_management:
            enabled: true
            path: '/session/manager/iframe'
        issuer_discovery:
            main:
                path: '/.well-known/webfinger'
                resource_repository: 'AppBundle\Entity\ResourceRepository'
                server: 'https://my-service.com:9000/'
        authorization:
            enabled: true
            path: '/authorize'
            #allow_scope_selection: true
            login_route_name: 'fos_user_security_login'
            pre_configured_authorization:
                enabled: true
            id_token_hint:
                enabled: true
#            request_object:
#                enabled: true
#                signature_algorithms: ['RS512', 'HS512']
#                claim_checkers: ['exp', 'iat', 'nbf', 'authorization_endpoint_aud']
#                header_checkers: ['crit']
#                encryption:
#                    enabled: true
#                    required: true
#                    key_set: 'jose.key_set.encryption'
#                    key_encryption_algorithms: ['RSA-OAEP-256']
#                    content_encryption_algorithms: ['A256CBC-HS512']
#                reference:
#                    enabled: true
#                    uris_registration_required: true
#            pre_configured_authorization:
#                enabled: true
#            enforce_secured_redirect_uri:
#                enabled: true
#            enforce_redirect_uri_storage:
#                enabled: true
#            enforce_state:
#                enabled: true
#            allow_response_mode_parameter:
#                enabled: true
    grant:
        authorization_code:
            enabled: true
            min_length: 50
            max_length: 100
            enforce_pkce: false
        refresh_token:
            enabled: true
            min_length: 50
            max_length: 100
            lifetime: 604800
        none:
            enabled: true
        implicit:
            enabled: true
        client_credentials:
            enabled: true
        resource_owner_password_credential:
            enabled: true
        id_token:
            enabled: true
            default_signature_algorithm: 'RS256'
            signature_algorithms: ['RS256', 'RS512', 'HS256', 'HS512', 'ES256', 'ES512']
            key_set: 'jose.key_set.signature'
            claim_checkers: ['exp', 'iat', 'nbf']
            header_checkers: ['crit']
            encryption:
                enabled: true
                required: false #Only for the id_token_hint. Should always be false.
                key_set: 'jose.key_set.encryption'
                key_encryption_algorithms: ['RSA-OAEP-256']
                content_encryption_algorithms: ['A256CBC-HS512']
#            pairwise_subject:
#                enabled: true
#                service: 'pairwise_subject_identifier'
#                is_default: true
        jwt_bearer:
            enabled: true
            issue_refresh_token: true
            signature_algorithms: ['RS256', 'RS512', 'HS256', 'HS512', 'ES256', 'ES512']
            claim_checkers: ['exp', 'iat', 'nbf']
            header_checkers: ['crit']
            encryption:
                enabled: true
                required: false
                key_set: 'jose.key_set.encryption'
                key_encryption_algorithms: ['RSA-OAEP-256']
                content_encryption_algorithms: ['A256CBC-HS512']
#    openid_connect:
#        claims_supported: ['sub', 'name', 'given_name', 'family_name', 'middle_name', 'nickname', 'preferred_username', 'profile', 'picture', 'website', 'email', 'email_verified', 'gender', 'birthdate', 'zoneinfo', 'locale', 'phone_number', 'phone_number_verified', 'address', 'updated_at']
#        claims_locales_supported: ['en', 'fr', 'de']
