imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: "%cookie_name%"
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_theme:
        - "FlobFoundationBundle:Form:foundation_form_div_layout.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOS User Bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: 'AppBundle\Entity\User'
    service:
        user_manager: 'app.user_manager'

flob_foundation:
    theme:
#        form: true
        knp_menu: true
        knp_paginator: false
        pagerfanta: false

jose:
    keys:
        access_token_signature_key:
            values:
                values:
                    kty: "oct"
                    kid: "ATSK0"
                    use: "sig"
                    alg: "HS512"
                    k: "AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow"
        access_token_key_encryption_key:
            values:
                values:
                    kty: "oct"
                    kid: "ATKEK0"
                    use: "enc"
                    alg: "A256KW"
                    k: "ABEiM0RVZneImaq7zN3u_wABAgMEBQYHCAkKCwwNDg8"
        id_token_private_signature_key:
            file:
                path: "%kernel.root_dir%/keys/RSA/private.key"
                password: "tests"
        id_token_public_signature_key:
            file:
                path: "%kernel.root_dir%/keys/RSA/public.key"
                additional_values:
                    kid: "2016-06-07"
                    use: "sig"
                    alg: "RS512"
    key_sets:
        public_keys:
            keys:
                id:
                    - 'jose.key.id_token_public_signature_key'
        private_keys:
            keys:
                id:
                    - 'jose.key.id_token_private_signature_key'
                    - 'jose.key.access_token_signature_key'
                    - 'jose.key.access_token_key_encryption_key'
    easy_jwt_creator:
        access_token:
            signature_algorithms:
                - 'HS512'
            key_encryption_algorithms:
                - 'A256KW'
            content_encryption_algorithms:
                - 'A256CBC-HS512'
            compression_methods:
                - 'DEF'
        id_token:
            signature_algorithms:
                - 'RS512'
            key_encryption_algorithms:
                - 'A128KW'
                - 'A192KW'
                - 'A256KW'
            content_encryption_algorithms:
                - 'A128CBC-HS256'
                - 'A192CBC-HS384'
                - 'A256CBC-HS512'
    easy_jwt_loader:
        access_token:
            signature_algorithms:
                - 'HS512'
            key_encryption_algorithms:
                - 'A256KW'
            content_encryption_algorithms:
                - 'A256CBC-HS512'
            compression_methods:
                - 'DEF'
            claim_checkers:
                - 'exp'
                - 'iat'
                - 'nbf'
            header_checkers:
                - 'crit'
        client_assertion:
            signature_algorithms:
                - 'HS512'
            key_encryption_algorithms:
                - 'A128KW'
                - 'A192KW'
                - 'A256KW'
            content_encryption_algorithms:
                - 'A128CBC-HS256'
                - 'A192CBC-HS384'
                - 'A256CBC-HS512'
            claim_checkers:
                - 'exp'
                - 'iat'
                - 'nbf'
            header_checkers:
                - 'crit'
    checkers:
        access_token:
            claims:
                - 'exp'
                - 'iat'
                - 'nbf'
            headers:
                - 'crit'
oauth2_server:
    scope:
        policy: 'none'
        available_scope:
            - 'openid'
            - 'email'
            - 'profile'
            - 'address'
            - 'phone'
            - 'offline_access'
    token_type_manager:
        default: Bearer
    bearer_token:
        query_string: true
        request_body: true
    mac_token:
        min_length: 50
        max_length: 100
        algorithm: 'hmac-sha-256'
        timestamp_lifetime: 10
    client_manager:
        client_class: 'AppBundle\Entity\Client'
        token_endpoint_auth_methods:
            none: true
            client_secret_post: true
            client_secret_basic:
                enabled: true
                realm: 'OAuth2 Server - Client Authentication'
            client_assertion_jwt:
                enabled: true
                jwt_loader: 'jose.jwt_loader.client_assertion'
                encryption:
                    enabled: true
                    jwk_set: 'jose.key_set.private_keys'
                    required: false
    refresh_token:
        token_class: 'AppBundle\Entity\RefreshToken'
        token_manager: 'app.refresh_token_manager'
        min_length: 50
        max_length: 100
    auth_code_grant_type:
        class: 'AppBundle\Entity\AuthCode'
        manager: 'app.auth_code_manager'
        min_length: 50
        max_length: 100
        enforce_pkce: true
        allow_public_clients: true
    implicit_grant_type:
        allow_confidential_clients: true
    token_endpoint:
        client_manager: 'app.client_manager'
        access_token_manager: 'app.access_token_manager'
        refresh_token_manager: 'app.refresh_token_manager'
        user_manager: 'app.user_manager'
    jwt_access_token:
        token_lifetime: 1800
        issuer: '%oauth2_issuer%'
        signature_algorithm: 'HS512'
        signature_key: 'jose.key.access_token_signature_key'
        jwt_creator: 'jose.jwt_creator.access_token'
        jwt_loader: 'jose.jwt_loader.access_token'
        token_encryption:
            enabled: true
            key_encryption_algorithm: 'A256KW'
            content_encryption_algorithm: 'A256CBC-HS512'
            key_encryption_key: 'jose.key.access_token_key_encryption_key'
    jwt_bearer_grant_type:
        jwt_loader: 'jose.jwt_loader.client_assertion'
        issue_refresh_token: false
        encryption:
            enabled: true
            jwk_set: 'jose.key_set.private_keys'
            required: true
    authorization_endpoint:
        allow_scope_selection: true
        login_route_name: "fos_user_security_login"
        request_object:
            jwt_loader: 'jose.jwt_loader.client_assertion'
            reference:
                enabled: true
                uris_registration_required: true
            jwkset: 'jose.key_set.private_keys'
        option:
            enforce_secured_redirect_uri: true
            enforce_redirect_uri_storage: true
            enforce_state: true
            allow_response_mode_parameter: true
    openid_connect:
        claims_supported:
            - "sub"
            - "name"
            - "given_name"
            - "family_name"
            - "middle_name"
            - "nickname"
            - "preferred_username"
            - "profile"
            - "picture"
            - "website"
            - "email"
            - "email_verified"
            - "gender"
            - "birthdate"
            - "zoneinfo"
            - "locale"
            - "phone_number"
            - "phone_number_verified"
            - "address"
            - "updated_at"
        claims_locales_supported:
            - "en"
            - "fr"
            - "de"
        pairwise_subject_identifier: 'app.hash_subject_type'
        jwks_uri:
            enabled: true
            public_keys: 'jose.key_set.public_keys'
        metadata:
            enabled: true
        session_management:
            enabled: true
        id_token:
            jwt_creator: 'jose.jwt_creator.id_token'
            signature_algorithm: 'RS512'
            signature_key: 'jose.key.id_token_private_signature_key'
        response_type:
            id_token:
                enabled: true
        userinfo_endpoint:
            enabled: true
            signature:
                enabled: true
                jwt_creator: 'jose.jwt_creator.id_token'
                signature_algorithm: 'RS512'
                signature_key: 'jose.key.id_token_private_signature_key'
        issuer_discovery:
            main:
                issuer: '%oauth2_issuer%'
                server: 'https://www.my.server/'
    security:
        access_token_handler: 'oauth2_server.security.access_token_manager_handler'
