imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: %cookie_name%
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#FOS User Bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        user_manager: app_bundle.user_manager

# OAuth2 Server Bundle
oauth2_server:
    scope:
        available_scope: 'scope1 scope2 scope3 scope4'
    unregistered_client:
        prefix: "U"
        client_class: AppBundle\Entity\UnregisteredClient
        client_manager_class: AppBundle\Entity\UnregisteredClientManager
    public_client:
        prefix: "p"
        client_class: AppBundle\Entity\PublicClient
        client_manager_class: AppBundle\Entity\PublicClientManager
    password_client:
        prefix: "P"
        client_class: AppBundle\Entity\PasswordClient
        client_manager_class: AppBundle\Entity\PasswordClientManager
        digest_authentication_key: abcdefghijklmnop
    refresh_token:
        token_class: AppBundle\Entity\RefreshToken
        token_manager: app_bundle.refresh_token_manager
    auth_code:
        class: AppBundle\Entity\AuthCode
        manager: app_bundle.auth_code_manager
    token_endpoint:
        access_token_manager: oauth2_server.jwt_access_token.manager
        refresh_token_manager: app_bundle.refresh_token_manager
        end_user_manager: app_bundle.user_manager
    authorization_endpoint:
        option:
            enforce_redirect_uri: false
            enforce_secured_redirect_uri: false
            enforce_registered_client_redirect_uris: false
            enforce_state: false
    jwt_access_token:
        issuer: My Authorization Server
        encrypt_tokens: true
        expose_public_keys: false
        signature_algorithm: HS512
        key_encryption_algorithm: A256KW
        content_encryption_algorithm: A256CBC-HS512
        signature_key:
            kid: SIGNATURE_KEY
            kty: oct
            use: sig
            k: AyM1SysPpbyDfgZld3umj1qzKObwVMkoqQ-EstJQLr_T-1qS0gZH75aKtMN3Yj0iPS4hcgUuTwjAzZr1Z9CAow
        encryption_key:
            kid: ENCRYPTION_KEY
            kty: oct
            use: enc
            k: ABEiM0RVZneImaq7zN3u_wABAgMEBQYHCAkKCwwNDg8
    jwt_bearer:
        allowed_encryption_algorithms: ['A256KW', 'A256CBC-HS512']
        allow_none_algorithm: false
        encryption_required: true
        expose_public_keys: true
        encryption_keys:
            ENCRYPTION_KEY:
                kid: ENCRYPTION_KEY
                kty: oct
                use: enc
                k: ABEiM0RVZneImaq7zN3u_wABAgMEBQYHCAkKCwwNDg8
    jwt_client:
        prefix: "J"
        client_class: AppBundle\Entity\JWTClient
        allowed_encryption_algorithms: ['A256KW', 'A256CBC-HS512']
        allow_none_algorithm: false
        encryption_required: true
        expose_public_keys: true
        encryption_keys:
            ENCRYPTION_KEY:
                kid: ENCRYPTION_KEY
                kty: oct
                use: enc
                k: ABEiM0RVZneImaq7zN3u_wABAgMEBQYHCAkKCwwNDg8

flob_foundation:
    theme:
        form: true
        knp_menu: true
        knp_paginator: false
        pagerfanta: false


jose:
    server_name: My Authorization Server
    storage:
        enabled: true
        class: AppBundle\Entity\Jot
    compression_methods:  ["DEF", "GZ", "ZLIB"]
