oauth2_server:
    http:
        client: 'Http\Client\Curl\Client'
        response_factory: 'Http\Factory\Diactoros\ResponseFactory'
        request_factory: 'Http\Factory\Diactoros\RequestFactory'
        uri_factory: 'Http\Factory\Diactoros\UriFactory'
    server_uri: "%env(OAUTH2_SERVER_URL)%"
    key_set:
        signature: "%env(OAUTH2_SERVER_PRIVATE_KEY_SET_SIGNATURE)%"
        encryption: "%env(OAUTH2_SERVER_PRIVATE_KEY_SET_ENCRYPTION)%"
    client:
        event_store: 'eventstore.client'
    user_account:
        manager: 'MyUserAccountManager'
        repository: 'MyUserAccountRepository'
    access_token:
        repository: 'MyAccessTokenRepository'
    resource_server:
        enabled: true
        repository: 'MyResourceServerRepository'
    scope:
        enabled: true
        repository: 'MyScopeRepository'
        policy:
            enabled: true
            by_default: 'none'
            error:
                enabled: true
            default:
                enabled: true
                scope: ['openid']
    token_type:
        default: 'Bearer'
        bearer_token:
            enabled: true
            realm: 'My super service'
            authorization_header: true
            query_string: true
            request_body: true
        mac_token:
            enabled: true
            min_length: 100
            max_length: 120
            algorithm: 'hmac-sha-256'
            timestamp_lifetime: 10
    token_endpoint_auth_method:
        none:
            enabled: true
        client_secret_post:
            enabled: true
            secret_lifetime: 0
        client_secret_basic:
            secret_lifetime: 0
            realm: 'My OAuth2 Server'
        client_assertion_jwt:
            enabled: true
            secret_lifetime: 0
            signature_algorithms: ['RS256', 'RS384', 'RS512', 'HS256', 'HS384', 'HS512', 'ES256', 'HS384', 'ES512', 'EdDSA']
            claim_checkers: ['exp', 'iat', 'nbf']
            header_checkers: ['crit']
            encryption:
                enabled: true
                required: false
                key_encryption_algorithms: ['RSA1_5', 'RSA-OAEP', 'RSA-OAEP-256', 'A128KW', 'A192KW', 'A256KW', 'A128GCMKW', 'A192GCMKW', 'A256GCMKW', 'PBES2-HS256+A128KW', 'PBES2-HS384+A192KW', 'PBES2-HS512+A256KW', 'ECDH-ES', 'ECDH-ES+A128KW', 'ECDH-ES+A192KW', 'ECDH-ES+A256KW']
                content_encryption_algorithms: ['A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512', 'A128GCM', 'A192GCM', 'A256GCM']
    endpoint:
        client_registration:
            enabled: true
            path: '/client/management'
            initial_access_token:
                enabled: true
                required: true
                realm: 'Client Registration'
                event_store: 'eventstore.initialaccesstoken'
            software_statement:
                enabled: true
                required: false
                allowed_signature_algorithms: ['RS512']
                key_set: "%env(OAUTH2_SERVER_PRIVATE_KEY_SET_SOFTWARE_STATEMENT)%"
        client_configuration:
            enabled: true
            realm: 'Client Configuration'
            path: '/client/configure/{client_id}'
        token_revocation:
            enabled: true
            path: '/token/revocation'
            allow_callback: true
        token_introspection:
            enabled: true
            path: '/token/introspection'
        token:
            enabled: true
            path: '/token/get'
        jwks_uri:
            enabled: true
            path: '/public.jwkset'
            key_set: "%env(OAUTH2_SERVER_PUBLIC_KEY_SET)%"
        metadata:
            enabled: true
            path: '/.well-known/openid-configuration'
            signature:
                enabled: true
                algorithm: 'RS256'
#            custom_routes:
#                service_documentation:
#                    route_name: 'service_documentation'
#                    route_parameters:
#                        'hello': 'developer'
#                op_policy_uri:
#                    route_name: 'op_policy_uri'
#                    route_parameters: []
#                op_tos_uri:
#                    route_name: 'op_tos_uri'
#                    route_parameters: []
            custom_values:
                acr_values_supported:
                    - 'urn:mace:incommon:iap:silver'
                    - 'urn:mace:incommon:iap:bronze'
                display_values_supported: ['page']
                ui_locales_supported: ['fr', 'en']
                claims_locales_supported: ['en', 'fr']
        session_management:
            enabled: true
            path: '/session/manager/iframe'
        issuer_discovery:
            main:
                path: '/.well-known/webfinger'
                resource_repository: 'MyResourceRepository'
                server: 'https://oidc.spomky-labs.com/'
        authorization:
            enabled: true
            path: '/authorize'
            #allow_scope_selection: true
            login_route_name: 'fos_user_security_login'
            response_mode:
                allow_response_mode_parameter: true
                form_post:
                    enabled: true
                    template: '@OAuth2FrameworkServerBundle/form_post/response.html.twig'
            request_object:
                enabled: true
                signature_algorithms: ['RS256', 'RS384', 'RS512', 'HS256', 'HS384', 'HS512', 'ES256', 'HS384', 'ES512', 'EdDSA']
                encryption:
                    enabled: true
                    required: false
                    key_encryption_algorithms: ['RSA1_5', 'RSA-OAEP', 'RSA-OAEP-256', 'A128KW', 'A192KW', 'A256KW', 'A128GCMKW', 'A192GCMKW', 'A256GCMKW', 'PBES2-HS256+A128KW', 'PBES2-HS384+A192KW', 'PBES2-HS512+A256KW', 'ECDH-ES', 'ECDH-ES+A128KW', 'ECDH-ES+A192KW', 'ECDH-ES+A256KW']
                    content_encryption_algorithms: ['A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512', 'A128GCM', 'A192GCM', 'A256GCM']
                reference:
                    enabled: true
                    uris_registration_required: true
            pre_configured_authorization:
                enabled: true
                event_store: 'eventstore.preconfiguredauthorization'
            allow_token_type_parameter: true
            enforce_secured_redirect_uri: true
            enforce_redirect_uri_storage: true
            enforce_state: true
    grant:
        authorization_code:
            enabled: true
            min_length: 50
            max_length: 100
            enforce_pkce: false
            event_store: 'eventstore.authcode'
        refresh_token:
            enabled: true
            min_length: 50
            max_length: 100
            lifetime: 604800
            event_store: 'eventstore.refreshtoken'
        none:
            enabled: false #Not fully implemented
        implicit:
            enabled: true
        client_credentials:
            enabled: true
        resource_owner_password_credential:
            enabled: true
        jwt_bearer:
            enabled: true
            issue_refresh_token: true
            signature_algorithms: ['RS256', 'RS384', 'RS512', 'HS256', 'HS384', 'HS512', 'ES256', 'HS384', 'ES512', 'EdDSA']
            claim_checkers: ['exp', 'iat', 'nbf']
            header_checkers: ['crit']
            encryption:
                enabled: true
                required: false
                key_encryption_algorithms: ['RSA1_5', 'RSA-OAEP', 'RSA-OAEP-256', 'A128KW', 'A192KW', 'A256KW', 'A128GCMKW', 'A192GCMKW', 'A256GCMKW', 'PBES2-HS256+A128KW', 'PBES2-HS384+A192KW', 'PBES2-HS512+A256KW', 'ECDH-ES', 'ECDH-ES+A128KW', 'ECDH-ES+A192KW', 'ECDH-ES+A256KW']
                content_encryption_algorithms: ['A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512', 'A128GCM', 'A192GCM', 'A256GCM']
    openid_connect:
        enabled: true
        pairwise_subject:
            enabled: true
            service: 'MyPairwiseSubjectIdentifier'
            is_default: true
        id_token:
            response_type:
                enabled: true
            lifetime: 1800
            default_signature_algorithm: 'RS256'
            signature_algorithms: ['RS256', 'RS384', 'RS512', 'HS256', 'HS384', 'HS512', 'ES256', 'HS384', 'ES512', 'EdDSA']
            claim_checkers: ['exp', 'iat', 'nbf']
            header_checkers: ['crit']
            encryption:
                enabled: true
                key_encryption_algorithms: ['RSA1_5', 'RSA-OAEP', 'RSA-OAEP-256', 'A128KW', 'A192KW', 'A256KW', 'A128GCMKW', 'A192GCMKW', 'A256GCMKW', 'PBES2-HS256+A128KW', 'PBES2-HS384+A192KW', 'PBES2-HS512+A256KW', 'ECDH-ES', 'ECDH-ES+A128KW', 'ECDH-ES+A192KW', 'ECDH-ES+A256KW']
                content_encryption_algorithms: ['A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512', 'A128GCM', 'A192GCM', 'A256GCM']
        id_token_hint:
            enabled: true
        userinfo_endpoint:
            enabled: true
            path: '/userinfo'
            signature:
                enabled: true
                signature_algorithms: ['RS256', 'RS384', 'RS512', 'HS256', 'HS384', 'HS512', 'ES256', 'HS384', 'ES512', 'EdDSA', 'none']
            encryption:
                enabled: true
                key_encryption_algorithms: ['RSA1_5', 'RSA-OAEP', 'RSA-OAEP-256', 'A128KW', 'A192KW', 'A256KW', 'A128GCMKW', 'A192GCMKW', 'A256GCMKW', 'PBES2-HS256+A128KW', 'PBES2-HS384+A192KW', 'PBES2-HS512+A256KW', 'ECDH-ES', 'ECDH-ES+A128KW', 'ECDH-ES+A192KW', 'ECDH-ES+A256KW']
                content_encryption_algorithms: ['A128CBC-HS256', 'A192CBC-HS384', 'A256CBC-HS512', 'A128GCM', 'A192GCM', 'A256GCM']
